### ISSUE TITLE
Feature Request: Check for Seccomp profiles on pods

### ISSUE THREAD

**Issue by dacappo** [zegl/kube-score#191]
Pods allow configuring a Seccomp profile for their pods to reduce the kernel attack surface by adding an annotation. e.g.:
```
annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
```
This would be a great security check to come with kube-score.

**Comment by zegl** [comment]
Hey, thanks for creating this issue and the accompanying PR!

Since the seccomp feature is in `alpha`, and only available for nodes on Linux (Windows nodes are in GA these days), I think that it would make sense to make this check opt-in instead of opt-out.

kube-score has a `--enable-optional-test` flag which is currently only used by the `container-resource-requests-equal-limits`-check, I think that we should follow the same pattern for this check.

**Comment by dacappo** [comment]
Hey, you've got a point there. Making the seccomp check optional is probably better for now. I just updated the PR. 

Btw. how do you think about the score grade? `Warning` seems to fit the case, but I wasn't really sure if there is any guidline.

**Comment by zegl** [comment]
Regarding the grading, there are no formal guidelines, so it's been mostly been based on gut feelings. Warning sounds appropriate in this case.
