### ISSUE TITLE
The statefulset-has-servicename check should check the StatefulSet SelectorLabels instead of Labels

### ISSUE THREAD

**Issue by j-martin** [zegl/kube-score#336]
**Which version of kube-score are you using?**

`kube-score version: 1.10.0, commit: 95faa2ad082e05d8b7637d0bd5e1ae00d1550260, built: 2020-11-07T14:17:50Z`

**What did you do?**

We've upgraded kube-score and we started seeing some errors due to `statefulset-has-servicename`. Looking at the code it looks like it expects the service selector labels to match the statefulset labels. https://github.com/zegl/kube-score/blob/ac55fb01452f9302941a5383ca7354ab711fb32c/score/apps/apps.go#L149 

This is not right as only the selectorLabels should be taken into consideration.

**What did you expect to see?**

Should use the `selectorLabels` of the StatefulSet.

**What did you see instead?** 

It uses the `labels` of the StatefulSet.

**Comment by zegl** [comment]
Sorry, late reply!

I think that there's a misunderstanding here. [Kubernetes requires](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations) that for every `StatefulSet` there is a headless `Service` created to match the `Pods` that the `StatefulSet` creates.

This check verifies that there exists a `Service` named `StatefulSet.Spec.ServiceName`, which `Service.Spec.Selector` matches the labels of the `Pods` (`StatefulSet.Spec.Template.Meta.Labels`).

If there is a bug in this implementation, It would be helpful if you (or anyone else finding this thread in the future) could send your YAML's where this bug was present, to reproduce the issue. 

It has nothing to do with `StatefulSet.Spec.Selector` having to match `StatefulSet.Spec.Template.Meta.Labels`. kube-score should probably have _another_ test for this, which I'm a bit surprised that we don't have actually. 

(cc @bynare)
